name: Seattle_ADU
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.11
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - pathlib
    - pyarrow
    - geopandas
    - cenpy